### ISSUE TITLE
boxplot turned silent after showing plot 

### ISSUE THREAD

**Issue by rrodionov** [kakearney/boxplot2-pkg#1]
nice function!
thanks for it.

my Matlab stops running boxplot after using boxplot2 - boxplot doesn't visualise a window, no error msgs.
using Win7, matlab R2016a

actually, it starts working once figure command called prior to calling boxplot

**Comment by kakearney** [comment]
Can you please post a small sample of code that demonstrates this problem?  Thus far I haven't been able to reproduce it on my machine; boxplot seems to work fine when called directly after boxplot2.

```matlab
x = (1:10);
y1 = randn(10,2,100);
y2 = randn(100,10);

boxplot2(y1,x);
hold on;

boxplot(y2,x, 'colors', 'g');
```

![boxplottest](https://user-images.githubusercontent.com/5015092/34541337-a46114f2-f08c-11e7-82be-9540313bab4e.png)

**Comment by rrodionov** [comment]
Thanks. Your piece of code works for me.
The issue seems with Figure window in case boxplot2 called incorrectly.
Pls perform the following step-by-step rather than a batch.

y2 = randn(100,10);

boxplot2(y2);
% ==== close the empty window and the following command will not open a new window
boxplot(y2,x, 'colors', 'g');

calling figure prior to boxplot would correct the situation.
figure; boxplot(...)

**Comment by kakearney** [comment]
Thanks for the example; it revealed that there were two separate bugs colliding here:

1) When I updated the code to deal with HG2 boxplot objects (R2016b+), the logic I used was not robust to a plotting just a single boxplot at each x datapoint (i.e npt x nx input or nx x 1 x npt input).  That's now been fixed, I believe.

2) In order to simplify the boxplot-coordinate calculations, I use a hidden figure to plot a temporary grouped bar graph.  But due to some lazy coding, if an error occurred within this plotting portion (as in your example), the hidden figure was left open, stealing focus from any future plotting commands.  I've now added a try-catch block to make sure that hidden figure is always closed, even if an error occurs.

If the latest version of the code doesn't fully fix the problems on your end, please reopen this issue and let me know!
